package com.intellimove.common.enums;

public enum DomainEventType {
    RIDE_REQUESTED,
    DRIVER_SEARCH_STARTED,
    DRIVER_ASSIGNED,
    DRIVER_REJECTED,
    DRIVER_ACCEPTED,
    DRIVER_ARRIVING,
    RIDE_STARTED,
    RIDE_COMPLETED,
    RIDE_CANCELLED,
    PAYMENT_INITIATED,
    PAYMENT_COMPLETED,
    PAYMENT_FAILED,
    REFUND_INITIATED,
    NOTIFICATION_REQUESTED,
    DRIVER_LOCATION_UPDATED,
    DRIVER_STATUS_CHANGED,
    USER_REGISTERED,
    SUPPORT_TICKET_CREATED
}
